apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 14
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: busybox
          image: busybox:1.25
          command:
            - /bin/sh
            - -ec
            - |
              echo "Going to sleep"
              tail -f /dev/null 
