/*
Copyright 2021 The Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kcp-dev/kcp/pkg/apis/apiresource/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NegociatedAPIResourceLister helps list NegociatedAPIResources.
type NegociatedAPIResourceLister interface {
	// List lists all NegociatedAPIResources in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.NegociatedAPIResource, err error)
	// Get retrieves the NegociatedAPIResource from the index for a given name.
	Get(name string) (*v1alpha1.NegociatedAPIResource, error)
	NegociatedAPIResourceListerExpansion
}

// negociatedAPIResourceLister implements the NegociatedAPIResourceLister interface.
type negociatedAPIResourceLister struct {
	indexer cache.Indexer
}

// NewNegociatedAPIResourceLister returns a new NegociatedAPIResourceLister.
func NewNegociatedAPIResourceLister(indexer cache.Indexer) NegociatedAPIResourceLister {
	return &negociatedAPIResourceLister{indexer: indexer}
}

// List lists all NegociatedAPIResources in the indexer.
func (s *negociatedAPIResourceLister) List(selector labels.Selector) (ret []*v1alpha1.NegociatedAPIResource, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NegociatedAPIResource))
	})
	return ret, err
}

// Get retrieves the NegociatedAPIResource from the index for a given name.
func (s *negociatedAPIResourceLister) Get(name string) (*v1alpha1.NegociatedAPIResource, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("negociatedapiresource"), name)
	}
	return obj.(*v1alpha1.NegociatedAPIResource), nil
}
