apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kcp:authenticated:universal-clusterworkspacetype-use
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kcp:universal-clusterworkspacetype-use
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
